// <auto-generated />
namespace SARC.WForm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingLocationAndSeatsTotand : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingLocationAndSeatsTotand));
        
        string IMigrationMetadata.Id
        {
            get { return "201707302017096_AddingLocationAndSeatsTotand"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
